### ISSUE TITLE
change mockery dependency to version 0.2.0

### ISSUE THREAD

**Issue by nsfinkelstein** [lbartnik/subprocess#30]
@lbartnik 

As discussed in https://github.com/n-s-f/mockery/issues/15, I've renamed `expect_no_calls` to `expect_called`.

However I cannot push this change to CRAN because subprocess depends on mockery, and this change breaks subprocess's test. Can you fix the dependency to version 0.2.0, so I can make breaking changes? I'd rather not have to keep `expect_no_calls` around for backwards compatibility at this stage - though if you would prefer, I could just keep it as an alias to `expect_called`.

Thanks

**Comment by lbartnik** [comment]
Yes, sure. Give me a few hours.

**Comment by nsfinkelstein** [comment]
Thanks! No rush at all.

**Comment by lbartnik** [comment]
Hey @n-s-f,

I'm afraid I can make the change in GitHub but I'm not ready to push a new version to CRAN yet. So you might need to leave a backwards-compatible API after all.

Lukasz

**Comment by nsfinkelstein** [comment]
No problem, will do.

Thanks
Noam

**Comment by nsfinkelstein** [comment]
@lbartnik Actually it seems to have made it onto CRAN in the iterm without the alias.
