### ISSUE TITLE
subprocess much slower than a classi process

### ISSUE THREAD

**Issue by Rloveeee** [lbartnik/subprocess#63]
Hello,

Thanks for this very interesting package.
I tested on my own coding and it's was very very slow compared to a classic process.
Is it expected ?

**_System confing_**
Windows 10
"R version 3.5.0 (2018-04-23)"

**_Reproducible code_** 

 ```
       ## on the main process
        xa=Sys.time()
	for(i in 1:10000){
		sd(rnorm(100000))
	}
	Sys.time()-xa # 1.30 min
       
        ## on a subprocess
	handle=spawn_process("C:/R/R-last-version/bin/x64/R.exe", c("--no-save")) 
	is.available<-function(handle){
		process_write(handle, '4+5\n')
		out=process_read(handle, PIPE_STDOUT, timeout = 1000)
		return("[1] 9" %in% out)
	}
	process_write(handle,'for(i in 1:1000){ sd(rnorm(100000)) }/n')
	xa=Sys.time()
	while(is.available(handle)){
		Sys.sleep(10)
	}
	Sys.time()-xa # 15.20 mins
```

**_Problem_**

Why subprocess are around 10 times slower than the main process ?
What shall I do to have subprocess with classic speed ? (So far, I failed to use implicit parallelization packaged due to strange behaviour on complex R codes)

Thanks

**Comment by lbartnik** [comment]
I have run this code in Linux and the times are very similar. I have also experienced slowdowns in Windows that unfortunately I cannot explain. There might be certain OS-level API calls to juggle process priorities but that's only a guess. I don't have the possibility to run this test under Windows at the moment so I cannot confirm your results.

If it makes sense, please take a look at the `processx` package. It might have what you need.

**Comment by Rloveeee** [comment]
Thanks, so far it's pretty hard to make work this processx but I am working on it
