### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by klosworks** [lbartnik/subprocess#66]
It appears that there is no licence given to use the library.

The LICENSE file just says:
YEAR: 2016
COPYRIGHT HOLDER: Lukasz A. Bartnik

Did you release this library just to show off, or are you counting on people to buy it from you?

**Comment by lbartnik** [comment]
Definitely to show off.

https://github.com/lbartnik/subprocess/blob/master/DESCRIPTION -> License
https://cran.r-project.org/web/licenses/MIT

**Comment by klosworks** [comment]
OK, good to know, thanks! :) 
Although I still think that if the LICENSE file says what it says, some people will assume that it is all there is to the license. My stance might become more relatable if you learn that I'm not an R programmer, but I'm here just for the C++ implementations.
